services:
  app:
    image: mentor_test:latest
    build: ./backend
    container_name: app_container
    ports:
      - "5001:5001"

  # ollama:
  #   image: ollama/ollama
  #   volumes:
  #     - ollama:/root/.ollama
  #   ports:
  #     - "11434:11434"
# volumes:
#   ollama:
